# Generated by Django 5.0.7 on 2024-07-31 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialquality',
            name='quality',
            field=models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], max_length=100),
        ),
        migrations.AlterModelTable(
            name='materialquality',
            table='construction_materialquality',
        ),
    ]
